COORD_TILES_FONT_SIZE = 18
COORD_TILES_FONT_COLOR = (0, 0, 0)
COORD_TILE_X_OFFSET = 9
COORD_TILE_Y_OFFSET = 20

TILE_YIELD_OVERLAY_FONT_SIZE = 18
TILE_YIELD_OVERLAY_FONT_COLOR = (200, 0, 0)
TILE_YIELD_OVERLAY_X_OFFSET = 9
TILE_YIELD_OVERLAY_Y_OFFSET = 20

# Enums?

TILE_SIZE = 46  # shouldn't be needed
TILES_RANGE = 7
