COORD_TILES_FONT_SIZE = 18
COORD_TILES_FONT_COLOR = (200, 50, 50)
COORD_TILES_FONT_COLOR = (0, 0, 0)
COORD_TILE_X_OFFSET = 9
COORD_TILE_Y_OFFSET = 20

TILE_SIZE = 46  # shouldn!t be needed
TILES_RANGE = 7